name: HNL
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=h5bd9786_13
  - afterimage=1.21=ha9998ff_1003
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py37h540881e_2
  - atk-1.0=2.36.0=h3371d22_4
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - binutils=2.36.1=hdd6e379_2
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_10
  - bleach=5.0.1=pyhd8ed1ab_0
  - brotlipy=0.7.0=py37h540881e_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-compiler=1.5.0=h166bdaf_0
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=ha61ee94_1013
  - certifi=2022.6.15=pyhd8ed1ab_1
  - cffi=1.15.1=py37h43b0acd_0
  - cfitsio=4.1.0=hd9d235c_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - compilers=1.5.0=ha770c72_0
  - conda=4.14.0=py37h89c1867_0
  - conda-package-handling=1.8.1=py37h540881e_1
  - cryptography=37.0.4=py37h38fbfac_0
  - cxx-compiler=1.5.0=h924138e_0
  - davix=0.8.2=h2122014_0
  - debugpy=1.6.3=py37hd23a5d3_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - fftw=3.3.10=nompi_hf0379b8_105
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fortran-compiler=1.5.0=h2a4ca65_0
  - freetype=2.12.1=hca18f0e_0
  - fribidi=1.0.10=h36c2ea0_0
  - ftgl=2.4.0=hbcb1f35_0
  - gcc=10.3.0=he2824d0_10
  - gcc_impl_linux-64=10.3.0=hf2f2afa_16
  - gcc_linux-64=10.3.0=hc39de41_10
  - gdk-pixbuf=2.42.8=hff1cb4f_0
  - gettext=0.19.8.1=h73d1719_1008
  - gfortran=10.3.0=h18518b4_10
  - gfortran_impl_linux-64=10.3.0=h73f4979_16
  - gfortran_linux-64=10.3.0=hb09a455_10
  - giflib=5.2.1=h36c2ea0_2
  - gl2ps=1.4.2=h0708190_0
  - glew=2.1.0=h9c3ff4c_2
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=5.0.1=h5abf519_0
  - gsl=2.7=he838d99_0
  - gsoap=2.8.119=h90a1d37_0
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h64030ff_2
  - gxx=10.3.0=he2824d0_10
  - gxx_impl_linux-64=10.3.0=hf2f2afa_16
  - gxx_linux-64=10.3.0=h2593f52_10
  - harfbuzz=5.1.0=hf9f4e7c_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py37h89c1867_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - ipykernel=6.15.2=pyh210e3f2_0
  - ipyparallel=8.4.1=pyhd8ed1ab_0
  - ipython=7.33.0=py37h89c1867_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.15.0=pyhd8ed1ab_0
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37h89c1867_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=h4a8ded7_13
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.83.1=h7bff187_0
  - libcxx=14.0.6=hf52228f_0
  - libcxxabi=14.0.6=ha770c72_0
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=10.3.0=he6cfe16_16
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgd=2.3.3=h18fbbfe_3
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.72.1=h2d90d5f_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=hf817b99_3
  - libllvm9=9.0.1=default_hc23dcda_7
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.37=h753d276_4
  - librsvg=2.54.4=h7abd40a_0
  - libsanitizer=10.3.0=h26c7422_16
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.2=h753d276_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-devel_linux-64=10.3.0=he6cfe16_16
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h0e0dad5_3
  - libtool=2.4.6=h9c3ff4c_1008
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_4
  - libxslt=1.1.35=h8affb1d_0
  - libzlib=1.2.12=h166bdaf_2
  - llvmlite=0.38.1=py37h0761922_0
  - lxml=4.9.1=py37h540881e_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py37h540881e_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - metakernel=0.29.2=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - nbclient=0.6.7=pyhd8ed1ab_0
  - nbconvert=7.0.0=pyhd8ed1ab_0
  - nbconvert-core=7.0.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.0.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - nlohmann_json=3.10.5=h27087fc_1
  - notebook=6.4.12=pyha770c72_0
  - numba=0.55.2=py37h43839f2_0
  - numpy=1.21.6=py37h976b520_0
  - openssl=1.1.1q=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.19.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.9=hc4f8a73_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - portalocker=2.5.1=py37h89c1867_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - psutil=5.9.2=py37h540881e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycosat=0.6.3=py37h540881e_1010
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py37h540881e_1
  - pysocks=1.7.1=py37h89c1867_5
  - pythia8=8.305=py37hcd2ae1e_0
  - python=3.7.10=hb7a2778_104_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pyzmq=23.2.1=py37h0c0c2a8_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - root=6.26.6=py37had91859_0
  - root_base=6.26.6=py37h3d4861d_0
  - ruamel_yaml=0.15.80=py37h540881e_1007
  - scitokens-cpp=0.7.1=h0255ffa_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.3.0=py37h89c1867_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.2=h4ff8645_1
  - sysroot_linux-64=2.17=h4a8ded7_13
  - tbb=2021.5.0=h924138e_1
  - terminado=0.15.0=py37h89c1867_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py37h540881e_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - vdt=0.4.3=h9c3ff4c_0
  - vector-classes=1.4.3=h924138e_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.6.12=h36c2ea0_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxcursor=1.2.0=h516909a_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxft=2.3.4=hc534e41_1
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xrootd=5.4.3=py37h62c5c55_1
  - xxhash=0.8.0=h7f98852_3
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h6239696_4
  - pip:
    - awkward==1.9.0
    - awkward0==0.15.5
    - boost-histogram==1.3.1
    - cachetools==5.2.0
    - click==8.1.3
    - cloudpickle==2.1.0
    - coffea==0.7.18
    - commonmark==0.9.1
    - correctionlib==2.1.0
    - cycler==0.11.0
    - docutils==0.19
    - fonttools==4.37.1
    - fsspec==2022.8.2
    - hist==2.6.1
    - histoprint==2.4.0
    - kiwisolver==1.4.4
    - law==0.1.7
    - lockfile==0.12.2
    - luigi==3.1.1
    - lz4==4.0.2
    - matplotlib==3.5.3
    - mplhep==0.3.26
    - mplhep-data==0.0.3
    - pandas==1.3.5
    - patsy==0.5.3
    - pillow==9.2.0
    - pyarrow==9.0.0
    - pydantic==1.10.1
    - python-daemon==2.3.1
    - pytz==2022.2.1
    - pyyaml==6.0
    - rich==12.5.1
    - scipy==1.7.3
    - statsmodels==0.13.5
    - tenacity==8.0.1
    - toml==0.10.2
    - uhi==0.3.1
    - uproot==4.3.5
    - uproot3==3.14.4
    - uproot3-methods==0.10.1
prefix: /afs/cern.ch/work/p/pdebryas/miniconda3/envs/HNL
